version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: on-failure
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker-1:
    image: confluentinc/cp-kafka
    restart: on-failure
    container_name: broker-1
    hostname: broker-1
    depends_on:
      - zookeeper
    extra_hosts:
      - 'localhost:127.0.0.1'
    ports:
      - 9091:9091
      - 9092:9092
    volumes:
      - /c/kafka/kf_data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'PLAINTEXT://broker-1:9092,INTERNAL://broker-1:9091'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092,INTERNAL://broker-1:9091'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  broker-2:
    image: confluentinc/cp-kafka
    restart: on-failure
    container_name: broker-2
    hostname: broker-2
    depends_on:
      - zookeeper
    extra_hosts:
      - 'localhost:127.0.0.1'
    ports:
      - 9093:9093
      - 9094:9094
    volumes:
      - /c/kafka1/kf_data:/var/lib/kafka1/data
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'PLAINTEXT://broker-2:9093,INTERNAL://broker-2:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9094,INTERNAL://broker-2:9093'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'

